repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v3.4.0"
    hooks:
      - id: check-merge-conflict
      - id: debug-statements

  - repo: local

    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]
        args: [--line-length=79, --target-version=py311]

      - id: autoflake
        name: autoflake
        entry: autoflake
        language: system
        types: [python]
        args: [--in-place, --remove-all-unused-imports, --remove-duplicate-keys, --exclude=apps.py]

      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [python]
        args: [
          "--ignore=E203,E266,E501,E704,W503,B905,B907",
          "--max-line-length=79",
          "--max-complexity=18",
          "--select=B,C,E,F,W,T4,B9",
          "--exclude=apps.py",
        ]

#      - id: isort
#        name: isort
#        entry: isort
#        language: system
#        types: [python]