version: '3.3'
services:
  nginx:
    restart: always
    image: nginx:1.21.3-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/app/eatpoint/static
      - media_value:/app/eatpoint/media

  backend:
    container_name: backend
    restart: always
    build:
      context: .
      dockerfile: ./eatpoint/Dockerfile
    entrypoint: /app/infra/backend-entrypoint.sh
    expose:
      - 8000
    volumes:
      - static_value:/app/eatpoint/static
      - media_value:/app/eatpoint/media
    env_file:
      - infra/.env
    depends_on:
      - db

  db:
    image: postgres:13.0-alpine
    restart: always
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - infra/.env
    expose:
      - 5432
    depends_on:
      - nginx

  redis:
    restart: unless-stopped
    image: redis:7.0.5-alpine
    container_name: redis
    expose:
      - 6379

  flower:
    restart: unless-stopped
    container_name: flower
    build:
      context: .
      dockerfile: ./eatpoint/Dockerfile
    entrypoint: /app/infra/flower-entrypoint.sh
    volumes:
      - static_value:/app/eatpoint/static
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - infra/.env
    ports:
      - "5555:5555"
    depends_on:
      - backend
      - redis

  worker:
    restart: unless-stopped
    container_name: worker
    build:
      context: .
      dockerfile: ./eatpoint/Dockerfile
    entrypoint: /app/infra/celery/worker-entrypoint.sh
    volumes:
      - static_value:/app/eatpoint/static
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - infra/.env
    depends_on:
      - backend
      - redis

  beat:
    restart: unless-stopped
    container_name: beat
    build:
      context: .
      dockerfile: ./eatpoint/Dockerfile
    entrypoint: /app/infra/celery/beat-entrypoint.sh
    volumes:
      - static_value:/app/eatpoint/static
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - infra/.env
    depends_on:
      - worker

volumes:
  static_value:
  media_value:
  postgres_data:
