# Generated by Django 4.2.5 on 2023-11-14 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("establishments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="establishment",
            name="poster",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="establishment/images/poster",
                verbose_name="Постер заведения",
            ),
        ),
    ]
