# Generated by Django 4.2.5 on 2023-11-24 20:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("establishments", "0006_alter_establishment_latitude"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Review",
        ),
    ]
