# Generated by Django 4.2.5 on 2023-12-21 10:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("establishments", "0007_delete_review"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Event",
        ),
        migrations.DeleteModel(
            name="TypeEvents",
        ),
    ]
