# Generated by Django 4.2.5 on 2023-12-21 20:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("establishments", "0008_delete_event_delete_typeevents"),
    ]

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.PositiveSmallIntegerField(
                        verbose_name="Номер столика"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "is_reserved",
                    models.BooleanField(
                        default=False, verbose_name="Забронирован"
                    ),
                ),
                (
                    "seats",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(
                                100,
                                message="Количество мест не может быть больше 100",
                            ),
                            django.core.validators.MinValueValidator(
                                0,
                                message="Количество мест не может быть меньше 0",
                            ),
                        ],
                        verbose_name="Количество мест",
                    ),
                ),
                (
                    "establishment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to="establishments.establishment",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tables",
                        to="establishments.zoneestablishment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Столик",
                "verbose_name_plural": "Столики",
            },
        ),
    ]
