# Generated by Django 4.2.5 on 2023-10-03 21:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("establishments", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Restaurant_reservations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="Электронная почта"),
                ),
                ("telephone", models.IntegerField(verbose_name="Телефон клиента")),
                (
                    "Number_of_guests",
                    models.CharField(
                        max_length=3,
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, message="Количество мест слишком маленькое"
                            ),
                            django.core.validators.MaxValueValidator(
                                100, message="Количество мест слишком большое"
                            ),
                        ],
                        verbose_name="Количество гостей",
                    ),
                ),
                (
                    "date_reservation",
                    models.DateField(verbose_name="Дата бронирования"),
                ),
                (
                    "start_time_reservation",
                    models.TimeField(verbose_name="Время начала бронирования"),
                ),
                (
                    "end_time_reservation",
                    models.TimeField(verbose_name="Время окончания бронирования"),
                ),
                (
                    "comment",
                    models.CharField(
                        max_length=200, verbose_name="Комментарий к бронированию"
                    ),
                ),
                (
                    "reminder_one_day",
                    models.BooleanField(
                        default=False,
                        verbose_name="Напоминание о бронировании за 1 день",
                    ),
                ),
                (
                    "reminder_three_hours",
                    models.BooleanField(
                        default=False, verbose_name="Напоминание за 3 часа"
                    ),
                ),
                (
                    "reminder_half_on_hour",
                    models.BooleanField(
                        default=False, verbose_name="Напоминание за 30 минут"
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        verbose_name="Статус бронирования Активен/Выполнен",
                    ),
                ),
                (
                    "establishment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservation",
                        to="establishments.establishment",
                        verbose_name="Ресторан",
                    ),
                ),
                (
                    "event",
                    models.ManyToManyField(
                        to="establishments.event", verbose_name="Выбор события"
                    ),
                ),
                (
                    "table",
                    models.ManyToManyField(
                        related_name="reservation",
                        to="establishments.tableestablishment",
                        verbose_name="Выбранный стол в ресторане",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservation",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
            },
        ),
    ]
