# Generated by Django 4.2.5 on 2023-10-12 13:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("establishments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=150, verbose_name="First name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(max_length=150, verbose_name="Last name"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="Электронная почта"
                    ),
                ),
                (
                    "telephone",
                    models.IntegerField(verbose_name="Телефон клиента"),
                ),
                (
                    "number_guests",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                1, message="Количество мест слишком маленькое"
                            ),
                            django.core.validators.MaxValueValidator(
                                20, message="Количество мест слишком большое"
                            ),
                        ],
                        verbose_name="Количество гостей",
                    ),
                ),
                (
                    "date_reservation",
                    models.DateField(
                        auto_now_add=True, verbose_name="Дата бронирования"
                    ),
                ),
                (
                    "start_time_reservation",
                    models.TimeField(verbose_name="Время начала бронирования"),
                ),
                (
                    "end_time_reservation",
                    models.TimeField(
                        verbose_name="Время окончания бронирования"
                    ),
                ),
                (
                    "comment",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Пожелания к заказу",
                    ),
                ),
                (
                    "reminder_one_day",
                    models.BooleanField(
                        default=False,
                        verbose_name="Напоминание о бронировании за 1 день",
                    ),
                ),
                (
                    "reminder_three_hours",
                    models.BooleanField(
                        default=False, verbose_name="Напоминание за 3 часа"
                    ),
                ),
                (
                    "reminder_half_on_hour",
                    models.BooleanField(
                        default=False, verbose_name="Напоминание за 30 минут"
                    ),
                ),
                (
                    "status",
                    models.BooleanField(
                        default=True,
                        verbose_name="Статус бронирования Активен/Выполнен",
                    ),
                ),
                (
                    "establishment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservation",
                        to="establishments.establishment",
                        verbose_name="Ресторан",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
            },
        ),
    ]
