# Generated by Django 4.2.5 on 2023-10-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservation", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="restaurant_reservations",
            name="event",
        ),
        migrations.AlterField(
            model_name="restaurant_reservations",
            name="telephone",
            field=models.CharField(max_length=10, verbose_name="Телефон клиента"),
        ),
    ]
