# Generated by Django 4.2.5 on 2023-10-31 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("establishments", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("reservation", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservationhistory",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservationhistory",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reservationhistory",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservationhistory",
                to="establishments.zoneestablishment",
                verbose_name="Выбранная зона в ресторане",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="establishment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservation",
                to="establishments.establishment",
                verbose_name="Ресторан",
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservation",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="establishments.zoneestablishment",
                verbose_name="Выбранная зона в ресторане",
            ),
        ),
        migrations.AddField(
            model_name="availability",
            name="zone",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="establishments.zoneestablishment",
            ),
        ),
    ]
