# Generated by Django 4.2.5 on 2023-10-12 13:18

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("reservation", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="telephone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None
            ),
        ),
    ]
