# Generated by Django 4.2.5 on 2023-10-03 22:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservation", "0002_remove_restaurant_reservations_event_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restaurant_reservations",
            name="Number_of_guests",
            field=models.IntegerField(
                max_length=3,
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Количество мест слишком маленькое"
                    ),
                    django.core.validators.MaxValueValidator(
                        100, message="Количество мест слишком большое"
                    ),
                ],
                verbose_name="Количество гостей",
            ),
        ),
    ]
