# Generated by Django 4.2.5 on 2023-12-21 20:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("establishments", "0009_table"),
        ("reservation", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={
                "ordering": ["-reservation_date"],
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
            },
        ),
        migrations.AlterModelOptions(
            name="reservationhistory",
            options={
                "ordering": ["-date_reservation"],
                "verbose_name": "Бронирование(архив)",
                "verbose_name_plural": "Бронирования(архив)",
            },
        ),
        migrations.RemoveField(
            model_name="confirmationcode",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="end_time_reservation",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="number_guests",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="status",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="zone",
        ),
        migrations.RemoveField(
            model_name="reservationhistory",
            name="end_time_reservation",
        ),
        migrations.RemoveField(
            model_name="reservationhistory",
            name="number_guests",
        ),
        migrations.RemoveField(
            model_name="reservationhistory",
            name="status",
        ),
        migrations.RemoveField(
            model_name="reservationhistory",
            name="user",
        ),
        migrations.RemoveField(
            model_name="reservationhistory",
            name="zone",
        ),
        migrations.AddField(
            model_name="confirmationcode",
            name="email",
            field=models.EmailField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reservation",
            name="is_accepted",
            field=models.BooleanField(
                default=False, verbose_name="Бронь подтверждена"
            ),
        ),
        migrations.AddField(
            model_name="reservation",
            name="is_visited",
            field=models.BooleanField(
                default=False, verbose_name="Заведение посещено"
            ),
        ),
        migrations.AddField(
            model_name="reservationhistory",
            name="is_accepted",
            field=models.BooleanField(
                null=True, verbose_name="Бронь подтверждена"
            ),
        ),
        migrations.AddField(
            model_name="reservationhistory",
            name="is_visited",
            field=models.BooleanField(
                null=True, verbose_name="Ресторан посещен"
            ),
        ),
        migrations.AddField(
            model_name="reservationhistory",
            name="reminder_half_on_hour",
            field=models.BooleanField(
                null=True, verbose_name="Напоминание за 30 минут"
            ),
        ),
        migrations.AddField(
            model_name="reservationhistory",
            name="reminder_one_day",
            field=models.BooleanField(
                null=True, verbose_name="Напоминание о бронировании за 1 день"
            ),
        ),
        migrations.AddField(
            model_name="reservationhistory",
            name="reminder_three_hours",
            field=models.BooleanField(
                null=True, verbose_name="Напоминание за 3 часа"
            ),
        ),
        migrations.AddField(
            model_name="reservationhistory",
            name="slots",
            field=models.TextField(
                blank=True,
                max_length=1500,
                verbose_name="Забронированные слоты",
            ),
        ),
        migrations.AlterField(
            model_name="confirmationcode",
            name="code",
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="date_reservation",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата брони"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Электронная почта"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="establishment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservation",
                to="establishments.establishment",
                verbose_name="Ресторан",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Имя"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="Фамилия"
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="start_time_reservation",
            field=models.CharField(
                choices=[
                    ("00:00", "00:00"),
                    ("00:30", "00:30"),
                    ("01:00", "01:00"),
                    ("01:30", "01:30"),
                    ("02:00", "02:00"),
                    ("02:30", "02:30"),
                    ("03:00", "03:00"),
                    ("03:30", "03:30"),
                    ("04:00", "04:00"),
                    ("04:30", "04:30"),
                    ("05:00", "05:00"),
                    ("05:30", "05:30"),
                    ("06:00", "06:00"),
                    ("06:30", "06:30"),
                    ("07:00", "07:00"),
                    ("07:30", "07:30"),
                    ("08:00", "08:00"),
                    ("08:30", "08:30"),
                    ("09:00", "09:00"),
                    ("09:30", "09:30"),
                    ("10:00", "10:00"),
                    ("10:30", "10:30"),
                    ("11:00", "11:00"),
                    ("11:30", "11:30"),
                    ("12:00", "12:00"),
                    ("12:30", "12:30"),
                    ("13:00", "13:00"),
                    ("13:30", "13:30"),
                    ("14:00", "14:00"),
                    ("14:30", "14:30"),
                    ("15:00", "15:00"),
                    ("15:30", "15:30"),
                    ("16:00", "16:00"),
                    ("16:30", "16:30"),
                    ("17:00", "17:00"),
                    ("17:30", "17:30"),
                    ("18:00", "18:00"),
                    ("18:30", "18:30"),
                    ("19:00", "19:00"),
                    ("19:30", "19:30"),
                    ("20:00", "20:00"),
                    ("20:30", "20:30"),
                    ("21:00", "21:00"),
                    ("21:30", "21:30"),
                    ("22:00", "22:00"),
                    ("22:30", "22:30"),
                    ("23:00", "23:00"),
                    ("23:30", "23:30"),
                ],
                max_length=5,
                null=True,
                verbose_name="Время начала брони",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="user",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservation",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reservationhistory",
            name="date_reservation",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата бронирования"
            ),
        ),
        migrations.AlterField(
            model_name="reservationhistory",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Электронная почта"
            ),
        ),
        migrations.AlterField(
            model_name="reservationhistory",
            name="establishment",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Ресторан"
            ),
        ),
        migrations.AlterField(
            model_name="reservationhistory",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Имя"
            ),
        ),
        migrations.AlterField(
            model_name="reservationhistory",
            name="reservation_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Дата создания"
            ),
        ),
        migrations.AlterField(
            model_name="reservationhistory",
            name="start_time_reservation",
            field=models.CharField(
                choices=[
                    ("00:00", "00:00"),
                    ("00:30", "00:30"),
                    ("01:00", "01:00"),
                    ("01:30", "01:30"),
                    ("02:00", "02:00"),
                    ("02:30", "02:30"),
                    ("03:00", "03:00"),
                    ("03:30", "03:30"),
                    ("04:00", "04:00"),
                    ("04:30", "04:30"),
                    ("05:00", "05:00"),
                    ("05:30", "05:30"),
                    ("06:00", "06:00"),
                    ("06:30", "06:30"),
                    ("07:00", "07:00"),
                    ("07:30", "07:30"),
                    ("08:00", "08:00"),
                    ("08:30", "08:30"),
                    ("09:00", "09:00"),
                    ("09:30", "09:30"),
                    ("10:00", "10:00"),
                    ("10:30", "10:30"),
                    ("11:00", "11:00"),
                    ("11:30", "11:30"),
                    ("12:00", "12:00"),
                    ("12:30", "12:30"),
                    ("13:00", "13:00"),
                    ("13:30", "13:30"),
                    ("14:00", "14:00"),
                    ("14:30", "14:30"),
                    ("15:00", "15:00"),
                    ("15:30", "15:30"),
                    ("16:00", "16:00"),
                    ("16:30", "16:30"),
                    ("17:00", "17:00"),
                    ("17:30", "17:30"),
                    ("18:00", "18:00"),
                    ("18:30", "18:30"),
                    ("19:00", "19:00"),
                    ("19:30", "19:30"),
                    ("20:00", "20:00"),
                    ("20:30", "20:30"),
                    ("21:00", "21:00"),
                    ("21:30", "21:30"),
                    ("22:00", "22:00"),
                    ("22:30", "22:30"),
                    ("23:00", "23:00"),
                    ("23:30", "23:30"),
                ],
                max_length=5,
                null=True,
                verbose_name="Время начала бронирования",
            ),
        ),
        migrations.CreateModel(
            name="Slot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "time",
                    models.CharField(
                        choices=[
                            ("00:00", "00:00"),
                            ("00:30", "00:30"),
                            ("01:00", "01:00"),
                            ("01:30", "01:30"),
                            ("02:00", "02:00"),
                            ("02:30", "02:30"),
                            ("03:00", "03:00"),
                            ("03:30", "03:30"),
                            ("04:00", "04:00"),
                            ("04:30", "04:30"),
                            ("05:00", "05:00"),
                            ("05:30", "05:30"),
                            ("06:00", "06:00"),
                            ("06:30", "06:30"),
                            ("07:00", "07:00"),
                            ("07:30", "07:30"),
                            ("08:00", "08:00"),
                            ("08:30", "08:30"),
                            ("09:00", "09:00"),
                            ("09:30", "09:30"),
                            ("10:00", "10:00"),
                            ("10:30", "10:30"),
                            ("11:00", "11:00"),
                            ("11:30", "11:30"),
                            ("12:00", "12:00"),
                            ("12:30", "12:30"),
                            ("13:00", "13:00"),
                            ("13:30", "13:30"),
                            ("14:00", "14:00"),
                            ("14:30", "14:30"),
                            ("15:00", "15:00"),
                            ("15:30", "15:30"),
                            ("16:00", "16:00"),
                            ("16:30", "16:30"),
                            ("17:00", "17:00"),
                            ("17:30", "17:30"),
                            ("18:00", "18:00"),
                            ("18:30", "18:30"),
                            ("19:00", "19:00"),
                            ("19:30", "19:30"),
                            ("20:00", "20:00"),
                            ("20:30", "20:30"),
                            ("21:00", "21:00"),
                            ("21:30", "21:30"),
                            ("22:00", "22:00"),
                            ("22:30", "22:30"),
                            ("23:00", "23:00"),
                            ("23:30", "23:30"),
                        ],
                        max_length=5,
                        verbose_name="Время бронирования",
                    ),
                ),
                (
                    "seats",
                    models.PositiveIntegerField(
                        verbose_name="Количество мест"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Статус слота"
                    ),
                ),
                (
                    "establishment",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="establishments.establishment",
                        verbose_name="Ресторан",
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="establishments.table",
                        verbose_name="Свободные столики",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="establishments.zoneestablishment",
                        verbose_name="Зона заведения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Свободный слот",
                "verbose_name_plural": "Свободные слоты",
            },
        ),
        migrations.AddField(
            model_name="reservation",
            name="slots",
            field=models.ManyToManyField(
                related_name="reservations",
                to="reservation.slot",
                verbose_name="Забронированные слоты",
            ),
        ),
    ]
