# Generated by Django 4.2.5 on 2023-10-04 18:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("establishments", "0002_initial"),
        ("reservation", "0003_alter_restaurant_reservations_number_of_guests"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Restaurant_reservations",
            new_name="EstablishmentReserv",
        ),
    ]
