# Generated by Django 4.2.5 on 2024-01-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservation", "0003_alter_reservation_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservationhistory",
            name="reservation_id",
            field=models.CharField(
                default=1, max_length=200, verbose_name="id брони"
            ),
            preserve_default=False,
        ),
    ]
