# Generated by Django 4.2.5 on 2023-10-12 16:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reservation", "0004_alter_reservation_telephone"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={
                "ordering": ["-date_reservation"],
                "verbose_name": "Бронирование",
                "verbose_name_plural": "Бронирования",
            },
        ),
        migrations.AlterField(
            model_name="reservation",
            name="end_time_reservation",
            field=models.CharField(
                choices=[
                    ("08:00", "08:00"),
                    ("08:30", "08:30"),
                    ("09:00", "09:00"),
                    ("09:30", "09:30"),
                    ("10:00", "10:00"),
                    ("10:30", "10:30"),
                    ("11:00", "11:00"),
                    ("11:30", "11:30"),
                    ("12:00", "12:00"),
                    ("12:30", "12:30"),
                    ("13:00", "13:00"),
                    ("13:30", "13:30"),
                    ("14:00", "14:00"),
                    ("14:30", "14:30"),
                    ("15:00", "15:00"),
                    ("15:30", "15:30"),
                    ("16:00", "16:00"),
                    ("16:30", "16:30"),
                    ("17:00", "17:00"),
                    ("17:30", "17:30"),
                ],
                max_length=145,
                verbose_name="Время окончания бронирования",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="first_name",
            field=models.CharField(max_length=150, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="last_name",
            field=models.CharField(max_length=150, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="number_guests",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(
                        1, message="Количество мест слишком маленькое"
                    ),
                    django.core.validators.MaxValueValidator(
                        100, message="Количество мест слишком большое"
                    ),
                ],
                verbose_name="Количество гостей",
            ),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="start_time_reservation",
            field=models.CharField(
                choices=[
                    ("08:00", "08:00"),
                    ("08:30", "08:30"),
                    ("09:00", "09:00"),
                    ("09:30", "09:30"),
                    ("10:00", "10:00"),
                    ("10:30", "10:30"),
                    ("11:00", "11:00"),
                    ("11:30", "11:30"),
                    ("12:00", "12:00"),
                    ("12:30", "12:30"),
                    ("13:00", "13:00"),
                    ("13:30", "13:30"),
                    ("14:00", "14:00"),
                    ("14:30", "14:30"),
                    ("15:00", "15:00"),
                    ("15:30", "15:30"),
                    ("16:00", "16:00"),
                    ("16:30", "16:30"),
                    ("17:00", "17:00"),
                    ("17:30", "17:30"),
                ],
                max_length=145,
                verbose_name="Время начала бронирования",
            ),
        ),
    ]
