# Generated by Django 4.2.5 on 2023-10-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("establishments", "0002_initial"),
        ("reservation", "0005_alter_establishmentreserv_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="establishmentreserv",
            name="table",
            field=models.ManyToManyField(
                related_name="reservations",
                to="establishments.tableestablishment",
                verbose_name="Выбранный стол в ресторане",
            ),
        ),
    ]
