# Generated by Django 4.2.5 on 2023-10-04 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("establishments", "0002_initial"),
        ("reservation", "0006_alter_establishmentreserv_table"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="establishmentreserv",
            name="table",
        ),
        migrations.AddField(
            model_name="establishmentreserv",
            name="table",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reservations",
                to="establishments.tableestablishment",
                verbose_name="Выбранный стол в ресторане",
            ),
            preserve_default=False,
        ),
    ]
