# Generated by Django 4.2.5 on 2023-12-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                fields=("establishment_id", "name", "date_start"),
                name="unique_event_in_establishment_per_day",
            ),
        ),
    ]
