# Generated by Django 4.2.5 on 2023-12-23 14:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_event_unique_event_in_establishment_per_day"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="date_end",
        ),
    ]
