# Generated by Django 4.2.5 on 2023-12-23 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("establishments", "0008_delete_event_delete_typeevents"),
        ("events", "0003_remove_event_date_end"),
    ]

    operations = [
        migrations.CreateModel(
            name="Reccurence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=30, verbose_name="Описание"),
                ),
                (
                    "days",
                    models.PositiveSmallIntegerField(
                        unique=True, verbose_name="Период в днях"
                    ),
                ),
            ],
            options={
                "verbose_name": "Период повторения события",
                "verbose_name_plural": "Периоды повторения событий",
                "ordering": ("days",),
            },
        ),
        migrations.RemoveField(
            model_name="eventphoto",
            name="event",
        ),
        migrations.AddField(
            model_name="event",
            name="photos",
            field=models.ManyToManyField(
                null=True, to="events.eventphoto", verbose_name="Фото события"
            ),
        ),
        migrations.AddField(
            model_name="eventphoto",
            name="establishment",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="establishments.establishment",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="RecurSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_start", models.DateField(verbose_name="Дата первого события")),
                ("date_end", models.DateField(verbose_name="Дата последнего события")),
                (
                    "recurrence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="events.reccurence",
                        verbose_name="Частота повторений",
                    ),
                ),
            ],
            options={
                "verbose_name": "Настройки повторения событий",
                "verbose_name_plural": "Настройки повторения событий",
            },
        ),
        migrations.AddField(
            model_name="event",
            name="recur_settings",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="events.recursetting",
            ),
        ),
    ]
