# Generated by Django 4.2.5 on 2023-12-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_reccurence_remove_eventphoto_event_event_photos_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="photos",
            field=models.ManyToManyField(
                blank=True, to="events.eventphoto", verbose_name="Фото события"
            ),
        ),
    ]
