# Generated by Django 4.2.5 on 2023-12-25 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0005_alter_event_photos"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recursetting",
            name="date_start",
        ),
        migrations.AlterField(
            model_name="event",
            name="type_event",
            field=models.ManyToManyField(
                to="events.typeevent", verbose_name="Тип события"
            ),
        ),
    ]
