# Generated by Django 4.2.5 on 2023-12-26 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0006_remove_recursetting_date_start_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="image",
        ),
        migrations.AddField(
            model_name="event",
            name="cover_image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="covered_events",
                to="events.eventphoto",
                verbose_name="Обложка события",
            ),
        ),
    ]
