# Generated by Django 4.2.5 on 2023-12-26 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0007_remove_event_image_event_cover_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={
                "default_related_name": "events",
                "ordering": ("date_start",),
                "verbose_name": "Событие",
                "verbose_name_plural": "События",
            },
        ),
        migrations.AlterField(
            model_name="event",
            name="cover_image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="covered_events",
                to="events.eventphoto",
                verbose_name="Обложка события",
            ),
        ),
    ]
